name = "wrangler-cloudflared-template"
type = "webpack"
webpack_config = "./packages/worker/webpack.config.js"
account_id = "5a883b414d4090a1442b20361f3c43a9"
workers_dev = true

[site]
bucket = "./packages/client/web-build"
entry-point = "./packages/worker"
